env_files = [
  {path = ".profile/py-linux-aarch64.env", profile = "py-linux-aarch64"},
  {path = ".profile/py-linux-x86_64.env", profile = "py-linux-x86_64"},
  {path = ".profile/py-windows-x86_64.env", profile = "py-windows-x86_64"},
]

[config]
default_to_workspace = false
skip_core_tasks = true

[env]
AUTHOR = {script = [''' git --no-pager log -n 1 | grep 'Author' | sed 's/Author:\s*//' ''']}
BRANCH = {script = [''' git branch | grep '\*' | awk '{print $2}' ''']}
DATE = {script = ["date +'%Y年%m月%d日%H:%M:%S'"]}
DAY = {script = ["git --no-pager log -n 1 --date=format:'%y%m%d%H' | grep Date | awk '{print $2}'"]}

[tasks.test]
script = ["cargo test ${FLAGS}"]

[tasks.expand]
script = ["cargo expand ${FLAGS}"]

[tasks.build]
script = ["cargo build ${FLAGS}"]

[tasks.run]
script = ["cargo run ${FLAGS}"]
