name: Build Lua
run-name: Lua building
on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read
  pull-requests: read

jobs:
  builds:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: ubuntu-22.04
            archit: x86_64
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-22.04
            archit: aarch64
            target: aarch64-unknown-linux-gnu
          - os: macos-13
            archit: x86_64
            target: x86_64-apple-darwin
          - os: macos-13
            archit: aarch64
            target: aarch64-apple-darwin
          - os: windows-2022
            archit: x86_64
            target: x86_64-pc-windows-gnu
    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Install Protoc
        if: ${{ matrix.platform.os != 'windows-2022' }}
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Rust
        if: ${{ matrix.platform.os != 'windows-2022' }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.platform.target }}
      - uses: Swatinem/rust-cache@v1
      - name: Install Cross Compiler
        if: ${{ matrix.platform.archit == 'aarch64' && matrix.platform.os == 'ubuntu-22.04' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends gcc-aarch64-linux-gnu libc6-dev-arm64-cross
      - name: Install MSYS2
        if: ${{ matrix.platform.os == 'windows-2022' }}
        uses: msys2/setup-msys2@v2
        with:
          install: >-
            mingw-w64-x86_64-rust
            mingw-w64-x86_64-protobuf
            mingw-w64-x86_64-lua
            mingw-w64-x86_64-pkg-config
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build
        if: ${{ matrix.platform.os != 'windows-2022' }}
        run: cargo build --release --no-default-features --features ffi_lua --target ${{matrix.platform.target}}
        working-directory: example
      - name: Build
        if: ${{ matrix.platform.os == 'windows-2022' }}
        run: cargo build --release --no-default-features --features ffi_lua --target ${{matrix.platform.target}}
        working-directory: example
        shell: msys2 {0}
